image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
  Qt5_INSTALL_DIR: 'C:\Qt\5.15.0\msvc2019_64'
  PATH: '%Qt5_INSTALL_DIR%\bin;%PATH%'
build_script:
- cmd: >-

    mkdir build

    cd build

    echo %PATH%

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release"

    cd ..

    mkdir distrib\flameshot

    windeployqt.exe --dir .\distrib\flameshot %APPVEYOR_BUILD_FOLDER%\build\Release\flameshot.exe

    copy "build\Release\flameshot.exe" "distrib\flameshot\flameshot.exe"

    copy "build\README.md" "distrib\flameshot\README.md"

    copy "build\LICENSE" "distrib\flameshot\LICENSE.txt"

    echo %flameshot_version% > "distrib\flameshot\version.txt"

    echo Build:%build_number% >> "distrib\flameshot\version.txt"

    echo %APPVEYOR_REPO_COMMIT% >> "distrib\flameshot\version.txt"

    copy "build\translations\Internationalization_*.qm" "distrib\flameshot\translations"

    cd distrib
    
    7z a flameshot.zip flameshot

artifacts:
    - path: build\src\flameshot.zip
      name: portable
    - path: build\src\Release\flameshot.exe
      name: exe_only